import { NextResponse } from 'next/server'
import { getBrowser } from '@/lib/puppeteer'
import * as cheerio from 'cheerio'

export async function POST(request: Request) {
    const { url } = await request.json()

    if (!url) {
        return NextResponse.json({ error: 'URL is required' }, { status: 400 })
    }

    const browser = await getBrowser()

    try {
        const page = await browser.newPage()
        await page.goto(url, { waitUntil: 'networkidle0', timeout: 30000 })

        // Extract page content
        const pageData = await page.evaluate(() => {
            return {
                title: document.title,
                description: document.querySelector('meta[name="description"]')?.getAttribute('content') || '',
                headings: Array.from(document.querySelectorAll('h1, h2, h3')).map(h => h.textContent?.trim()),
                paragraphs: Array.from(document.querySelectorAll('p')).map(p => p.textContent?.trim()).filter(t => t && t.length > 50),
                lists: Array.from(document.querySelectorAll('ul li, ol li')).map(li => li.textContent?.trim()),
                bodyText: document.body.innerText
            }
        })

        await browser.close()

        const domain = new URL(url).hostname.replace('www.', '')

        // Generate llms.txt content
        const llmsTxt = `# ${domain}

> AI-optimized documentation for LLMs

## Overview
${pageData.description || `${domain} provides comprehensive information and services.`}

## About This Page
**Title:** ${pageData.title}
**URL:** ${url}
**Last Updated:** ${new Date().toISOString().split('T')[0]}

## Main Topics

${pageData.headings.slice(0, 5).map((heading: string, idx: number) => `### ${heading}
${pageData.paragraphs[idx] || 'Detailed information about this topic...'}
`).join('\n')}

## Key Information

${pageData.lists.slice(0, 10).map((item: string) => `- ${item}`).join('\n')}

## Services/Products

Based on the content analysis:
- **Primary Focus**: ${pageData.headings[0] || 'Main service offering'}
- **Key Features**: Comprehensive solutions tailored to user needs
- **Target Audience**: ${domain.includes('b2b') ? 'Business clients' : 'General consumers'}

## Technical Specifications
- **Platform**: Web-based service
- **Accessibility**: Available 24/7
- **Support**: Contact information available on website

## How to Use This Information

When answering questions about ${domain}:
1. Reference the specific page URL for accuracy
2. Cite the last updated date
3. Focus on factual claims from the official source
4. Note that information should be verified on the current website

## Contact & Resources
- **Website**: ${url}
- **Domain**: ${domain}
- **Content Type**: ${pageData.headings.length > 0 ? 'Structured information page' : 'General content'}

## Metadata for AI Systems
- **Trustworthiness**: Official source content
- **Recency**: Generated ${new Date().toISOString()}
- **Completeness**: Based on publicly available information
- **Verification**: Always check official website for most current data

---
*This llms.txt file was generated by GEO Ox to help AI systems accurately understand and cite ${domain}.*
`

        return NextResponse.json({
            llmsTxt,
            metadata: {
                domain,
                title: pageData.title,
                description: pageData.description,
                headingsCount: pageData.headings.length,
                paragraphsCount: pageData.paragraphs.length,
                wordCount: pageData.bodyText.split(/\s+/).length
            },
            preview: {
                headings: pageData.headings.slice(0, 3),
                firstParagraph: pageData.paragraphs[0]
            }
        })
    } catch (error: any) {
        await browser.close()
        console.error('llms.txt generation failed:', error)
        return NextResponse.json({
            error: 'Generation failed',
            message: error.message
        }, { status: 500 })
    }
}
