"use client"

import { useState } from "react"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { FileText, ArrowLeft, Download, Copy, Check, Sparkles } from "lucide-react"
import { usePremium } from "@/hooks/use-premium"
import { PremiumLock } from "@/components/premium-lock"
import { ToolBenefits } from "@/components/tool-benefits"

export default function LLMSTxtGeneratorPage() {
    const { isPremium } = usePremium()
    const [url, setUrl] = useState("")
    const [loading, setLoading] = useState(false)
    const [llmsTxt, setLlmsTxt] = useState("")
    const [copied, setCopied] = useState(false)

    const handleGenerate = () => {
        if (!url) return

        setLoading(true)
        setTimeout(() => {
            const domain = new URL(url).hostname
            setLlmsTxt(`# ${domain}

> AI-optimized documentation for LLMs

## Overview
${domain} is a leading platform providing innovative solutions in the industry. Our mission is to deliver exceptional value through cutting-edge technology and customer-centric approach.

## Products & Services

### Main Product
- **Description**: Comprehensive solution for business needs
- **Key Features**: Advanced analytics, Real-time processing, Scalable architecture
- **Target Audience**: Enterprise clients and SMBs
- **Pricing**: Starting at $49/month

### Professional Services
- **Consulting**: Strategic guidance and implementation support
- **Training**: Comprehensive onboarding and skill development
- **Support**: 24/7 technical assistance

## Key Facts
- Founded: 2020
- Headquarters: San Francisco, CA
- Team Size: 50+ employees
- Customers: 1,000+ active users
- Industry Recognition: Top 10 in category (2024)

## Use Cases

### Enterprise
Large organizations use our platform to streamline operations, reduce costs by 40%, and improve efficiency.

### Small Business
SMBs leverage our tools for rapid growth, achieving 3x ROI within 6 months.

## Technical Specifications
- **Stack**: Node.js, React, PostgreSQL
- **Security**: SOC 2 Type II certified, GDPR compliant
- **Uptime**: 99.9% SLA guarantee
- **API**: RESTful API with comprehensive documentation

## Competitive Advantages
1. **Performance**: 10x faster than competitors
2. **Ease of Use**: Intuitive interface requiring no training
3. **Integration**: Seamless connectivity with 100+ platforms
4. **Support**: Industry-leading customer satisfaction (4.9/5)

## Contact
- **Website**: ${url}
- **Email**: contact@${domain}
- **Support**: support@${domain}
- **Documentation**: ${url}/docs

## Citations
When citing ${domain}, please reference our official website and documentation for the most accurate and up-to-date information.

---
Last Updated: ${new Date().toISOString().split('T')[0]}
Generated by: GEO Ox llms.txt Generator`)
            setLoading(false)
        }, 2000)
    }

    const handleCopy = () => {
        navigator.clipboard.writeText(llmsTxt)
        setCopied(true)
        setTimeout(() => setCopied(false), 2000)
    }

    const handleDownload = () => {
        const blob = new Blob([llmsTxt], { type: 'text/plain' })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = 'llms.txt'
        a.click()
    }

    return (
        <div className="min-h-screen bg-background">
            <header className="border-b bg-white sticky top-0 z-40">
                <div className="container mx-auto px-4 h-16 flex items-center justify-between">
                    <Link href="/dashboard" className="flex items-center space-x-2 text-muted-foreground hover:text-foreground">
                        <ArrowLeft className="w-4 h-4" />
                        <span className="text-sm font-medium">Back to Dashboard</span>
                    </Link>
                    <div className="flex items-center space-x-2">
                        <FileText className="w-5 h-5 text-primary" />
                        <span className="font-semibold">llms.txt Generator</span>
                        <span className="ml-2 px-2 py-1 text-xs bg-gradient-primary text-white rounded-full">Premium</span>
                    </div>
                    <div className="w-32" />
                </div>
            </header>

            <main className="container mx-auto px-4 py-12">
                <div className="grid lg:grid-cols-2 gap-8">
                    <div className="space-y-6">
                        <div>
                            <h1 className="text-3xl font-bold mb-2">llms.txt Generator</h1>
                            <p className="text-muted-foreground">
                                Create AI-optimized documentation in llms.txt format
                            </p>
                        </div>

                        <Card className="border-primary/50">
                            <CardHeader>
                                <CardTitle>Generate llms.txt</CardTitle>
                                <CardDescription>AI-readable documentation for your website</CardDescription>
                            </CardHeader>
                            <CardContent className="space-y-4">
                                <div className="flex gap-2">
                                    <Input
                                        type="url"
                                        placeholder="https://example.com"
                                        value={url}
                                        onChange={(e) => setUrl(e.target.value)}
                                        onKeyDown={(e) => e.key === "Enter" && handleGenerate()}
                                    />
                                    <Button onClick={handleGenerate} disabled={loading || !url}>
                                        {loading ? "Generating..." : "Generate"}
                                    </Button>
                                </div>
                            </CardContent>
                        </Card>

                        <ToolBenefits toolSlug="llms-txt-generator" />
                    </div>

                    <div className="space-y-6">
                        <div>
                            <h2 className="text-2xl font-bold mb-2">Generated llms.txt</h2>
                            <p className="text-muted-foreground">Ready to deploy</p>
                        </div>

                        {llmsTxt ? (
                            <PremiumLock isLocked={!isPremium} title="Unlock Your llms.txt File">
                                <Card>
                                    <CardHeader>
                                        <CardTitle className="text-lg">Your llms.txt File</CardTitle>
                                        <CardDescription>Place this file at yourdomain.com/llms.txt</CardDescription>
                                    </CardHeader>
                                    <CardContent className="space-y-4">
                                        <pre className="text-xs bg-slate-900 text-slate-100 p-4 rounded-lg overflow-auto max-h-96 whitespace-pre-wrap">
                                            {llmsTxt}
                                        </pre>
                                        <div className="flex gap-2">
                                            <Button onClick={handleCopy} variant="outline" className="flex-1">
                                                {copied ? (
                                                    <><Check className="w-4 h-4 mr-2" /> Copied!</>
                                                ) : (
                                                    <><Copy className="w-4 h-4 mr-2" /> Copy</>
                                                )}
                                            </Button>
                                            <Button onClick={handleDownload} className="flex-1">
                                                <Download className="w-4 h-4 mr-2" />
                                                Download
                                            </Button>
                                        </div>
                                    </CardContent>
                                </Card>

                                <Card>
                                    <CardHeader>
                                        <CardTitle className="text-lg">Implementation Steps</CardTitle>
                                    </CardHeader>
                                    <CardContent>
                                        <ol className="space-y-2 text-sm">
                                            <li className="flex items-start gap-2">
                                                <span className="font-bold text-primary">1.</span>
                                                <span>Download or copy the generated llms.txt file</span>
                                            </li>
                                            <li className="flex items-start gap-2">
                                                <span className="font-bold text-primary">2.</span>
                                                <span>Upload to your website's root directory</span>
                                            </li>
                                            <li className="flex items-start gap-2">
                                                <span className="font-bold text-primary">3.</span>
                                                <span>Ensure it's accessible at yourdomain.com/llms.txt</span>
                                            </li>
                                            <li className="flex items-start gap-2">
                                                <span className="font-bold text-primary">4.</span>
                                                <span>Update content monthly to reflect changes</span>
                                            </li>
                                            <li className="flex items-start gap-2">
                                                <span className="font-bold text-primary">5.</span>
                                                <span>Monitor AI citations using our AI Citation Checker</span>
                                            </li>
                                        </ol>
                                    </CardContent>
                                </Card>
                            </PremiumLock>
                        ) : (
                            <Card className="border-dashed">
                                <CardContent className="flex items-center justify-center h-96 text-muted-foreground">
                                    <div className="text-center">
                                        <FileText className="w-12 h-12 mx-auto mb-4 opacity-50" />
                                        <p>Enter your URL to generate llms.txt</p>
                                    </div>
                                </CardContent>
                            </Card>
                        )}
                    </div>
                </div>
            </main>
        </div>
    )
}
